### PR TITLE
feat(nuxt)!: rewrite nuxt module

### PR DESCRIPTION
**Pull request by pi0**
This PR rewrites the Pinia+Nuxt module for best Nuxt 3 and Bridge compatibility 💛 

Testing repo with published package: https://github.com/pi0/nuxt-tests/tree/pinia

Changes:
- Add pinia as a dependency -- Nuxt modules are supposed to be standalone and provide integration out of the box
- Migrate back to kit -- However using kit is not documented yet and might change, it will make stability much better than not using it and without it we have to inline bridge support
- Split vue 2 (bridge) and vue 3 plugins
- Remove deprecated `ctx.pinia` 
- Nuxt 2 without bridge is not supported anymore
- Drop `.$nuxt` support to prefer `useNuxtApp`

TODO:
- [ ] Use resolveModule from kit to respect search path for pinia
- [ ] Detect bridge || nuxt 3 (https://github.com/nuxt/nuxt.js/issues/11869)
- [ ] Fix config types
- [ ] Fix runtime types
- [x] Auto import for pinia

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Is there something I can help with? (It's the last missing piece for my migration to bridge)

**Comment by yassilah** [comment]
Hi! I'd love to help too if there's anything I can do 🙂

**Comment by pi0** [comment]
Thanks, @yassilah @tobiasdiez 💚  PR is pending for Nuxt 3 module tooling. Expect it ready soon :)

**Comment by psycongaroo** [comment]
hope see it soon <3

**Comment by DamianGlowala** [comment]
Any chance to see this PR merged in the near future? :) Seems like the following code is never taken into account with Nuxt 2 + Bridge:

```
const piniaSharedStatePlugin: Plugin = ({ $pinia }) => {
    $pinia.use(({ store }) => {
        console.log("REGISTERED PLUGIN");
    });
};

export default piniaSharedStatePlugin;
```

**Comment by AndreyYolkin** [comment]
I understand, that you have a lot of work on Nuxt3 RC, but could you clarify the current status of this PR?

**Comment by pi0** [comment]
Reworking in a new PR~> nuxt/nuxt.js#12596

**Pull request closed without merging**
