### PR TITLE
Added translation of documentation into Russian

### PR DESCRIPTION
**Pull request by Ibochkarev**
Starting translation into Russian and configuring the locale

### CODE REVIEW

**Comment by Ibochkarev** [comment]
@posva Good day! Are there any difficulties in the approval of this PR?

**Comment by Ibochkarev** [comment]
Up!

**Comment by posva** [comment]
Thanks for the PR but please don't "Up!" the PR because it creates notifications for the maintainers. This is already in my Todo list, we are adding some translation contribution guidelines to the router and pinia to make the process more clear. I will come back to you as soon as I can. Thanks!

**Comment by Ibochkarev** [comment]
@posva Good afternoon! 
Is there any chance that this PR will be accepted?

**Review by posva — CHANGES_REQUESTED** [review]
Can you make this hosted outside of this repo? Similar to the other translations. It should also be the work of multiple people (like the other translations) to ensure it's kept up to date. I think https://github.com/translation-gang was doing Russian Translations

**Comment by Leronez** [comment]
This pr is no longer needed, as a link to the Russian documentation has been added in another pr, #2438 . I contacted @Ibochkarev , and he agreed to contribute his translations to the current translation repository for Pinia (https://github.com/translation-ru/pinia/).

**Comment by posva** [comment]
Thanks!

**Pull request closed without merging**
