### PR TITLE
docs(zh): sync with English version

### PR DESCRIPTION
**Pull request by awxiaoxian2020**

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@KimYangOfCat Could you review these changes? :)

**Comment by awxiaoxian2020** [comment]
@posva Do we need add `docs/.vitepress/cache` to `.gitignore`?

**Comment by posva** [comment]
This file was included by accident.

Oops, I meant to comment at
- https://github.com/vuejs/pinia/pull/1972

**Comment by posva** [comment]
I had to do solve some manual merge conflicts. I'm going to give this a look and try to merge it to the other branch to avoid any further issues 😅

**Review by posva — APPROVED** [review]
感谢!

**Pull request merged**
