### PR TITLE
fix: minor grammar issues

### PR DESCRIPTION
**Pull request by icarusgk**
Fix minor grammar issues on file `packages/docs/api/interfaces/pinia_testing.TestingOptions.md`

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Can you add the changes to the source code instead? These files are generated. Thank you!

**Comment by icarusgk** [comment]
Of course! but, which branch/repo is the source code? 😅

**Comment by posva** [comment]
same branch: v2, packages/pinia/src

**Comment by icarusgk** [comment]
Thanks for your guidance 😄

**Review by posva — APPROVED** [review]
Thanks!

**Pull request merged**
