### PR TITLE
Docs: Add section to show using a store outside Vue.

### PR DESCRIPTION
**Pull request by cwilvx**
This pull request adds a section to show how to use a Pinia store outside a Vue file to the Pinia docs.

### CODE REVIEW

**Comment by posva** [comment]
What is this adding? I don't understand what new information it brings

**Comment by cwilvx** [comment]
@posva  

Under [Using a store outside of a component](https://pinia.vuejs.org/core-concepts/outside-component-usage.html), the Pinia docs just mention that ` ... if the pinia instance cannot be automatically injected, you have to manually provide it to the useStore() function` but doesn't show how to actually do so. 

This pull request adds an example to demonstrate how to inject a Pinia store outside Vue.

**Comment by posva** [comment]
Yeah, that's explained in the SSR docs

**Comment by cwilvx** [comment]
@posva 

What about client side rendered apps? Some people don't use SSR, they expect to find the info on the `Using a store outside of a component` page.

**Comment by posva** [comment]
Your example is just showing how to pass a store as an argument of a function. Are you trying to show anything more?

**Comment by cwilvx** [comment]
It's just showing passing a store as an argument as a way of injecting a store outside a vue instance. Nothing more.

**Comment by posva** [comment]
I see. Thank you but I don't think this should be in the docs.

**Pull request closed without merging**
