### PR TITLE
docs: Update getters.md about parameter example

### PR DESCRIPTION
**Pull request by PineappleAttack**
Adding an example of a getter in a setup store with a parameter

### CODE REVIEW

**Comment by posva** [comment]
Thanks but already there: https://pinia.vuejs.org/core-concepts/getters.html#passing-arguments-to-getters

**Comment by PineappleAttack** [comment]
> Thanks but already there: https://pinia.vuejs.org/core-concepts/getters.html#passing-arguments-to-getters

Sorry but I still see only an example for the option api not for setup variant.

**Comment by hcmlopes** [comment]
I think this should be reopened. I just spent an hour googling and this example is not in the docs at all. 

There are some small nuances that should be in the docs for example your state being a `ref()`

**Comment by PineappleAttack** [comment]
> I think this should be reopened. I just spent an hour googling and this example is not in the docs at all.
> 
> There are some small nuances that should be in the docs for example your state being a `ref()`

Thanks, I have not the rights to reopen it, but maybe @posva can do it?

**Comment by posva** [comment]
In the future, I want to add a way to toggle between option and setup stores (like the vue docs)

**Pull request closed without merging**
