### PR TITLE
chore: add portuguese documentation link

### PR DESCRIPTION
**Pull request by nazarepiedady**
In this pull request, I am adding the link to the Portuguese version of the documentation.

### CODE REVIEW

**Comment by nazarepiedady** [comment]
@posva @Jinjiang @pi0 @patak-dev

Again, sorry to bother you but could you merge this little change?

**Review by posva — COMMENTED** [review]
Are you doing the translations only by yourself? It would be better if it's maintained updated by a team and hosted on an org like https://github.com/vuejs-br/br.vuejs.org where other Portuguese translations are hosted.

**Comment by nazarepiedady** [comment]
@posva, Yes I am doing the translation mainly alone but I am accountable so I do not intend to stop to maintain the translation. 😊

Also, I am the person that started translating the [vuejs-translations/docs-pt](https://github.com/vuejs-translations/docs-pt) and [vitejs/docs-pt](https://github.com/vitejs/docs-pt) and also I am their principal maintainer. ☝️

So do not worry because the project is in good hands 💪 😉.

**Comment by nazarepiedady** [comment]
@posva do you have some time to merge this pull request or could you give it to someone to do it?

**Comment by posva** [comment]
No need to ping like this @nazarepiedady 😉 
I will look it when I have time, thanks

**Review by posva — APPROVED** [review]
Thanks a lot! ❤️
I think you should move the repository to https://github.com/vuejs-translations/ too to give it more visibility among other Portuguese speakers who want to contribute

**Comment by nazarepiedady** [comment]
@posva the https://github.com/vuejs-translations/ is receiving other translations project beyond the vue documentation?

**Comment by posva** [comment]
maybe not but I think it should, it would make things easier

**Comment by Jinjiang** [comment]
@nazarepiedady for maintaining the translations of other official vue projects in `vuejs-translations` org, let me think about that a little bit more and get back to you. It's a good idea in general. We can create another issue or discussion topic for this necessarily.

Beside that, feel free to take a look at this PR and relevant discussion: https://github.com/vuejs/router/pull/1855. That is a new translation workflow which I'm trying recently. I'd like to recommend that to other vue-ecosystem projects. It's more lightweight than the guidelines of vuejs.org translation. Just FYI.

**Comment by nazarepiedady** [comment]
@Jinjiang is it the `vuejs-translations` receiving the translations for other `vuejs` projects? I was not informed about this.

Is the process the same as the one defined for the `vuejs` documentation itself?

**Pull request merged**
