### PR TITLE
fix(nuxt3): Rename `app` to `vueApp`

### LINKED ISSUE #730: Problem with Pinia and latest build of Nuxt3
Today I updated Nuxt 3 to the latest release and Pinia stopped working. Here is the repository with a totally clear installation of Nuxt 3 (on `main` branch) and Pinia (on `test/pinia`):

https://github.com/lukaszflorczak/nuxt3-demo/tree/test/pinia

To reproduce the problem, just run the project. You should see:

Zrzut ekranu 2021-10-19 o 08 13 43

```
Accessing app is not supported in Nuxt3.
Cannot read properties of undefined (reading 'use')
  at PiniaNuxtPlugin (file://./.nuxt/dist/server/server.mjs:2053:17)  
  at file://./.nuxt/dist/server/server.mjs:201:27  
  at file://./.nuxt/dist/server/server.mjs:187:38  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:227:13)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:187:10)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:192:11)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:34:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:163:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:572:19)
```

Yesterday I tested Pinia on version `3.0.0-27242646.117b3aa` and it has worked yet.

### PR DESCRIPTION
**Pull request by lukaszflorczak**
Resolve #730

Source: nuxt/bridge#302

🙏 Thanks to @productdevbook

### CODE REVIEW

**Review by productdevbook — APPROVED** [review]

**Comment by posva** [comment]
Did you check if this works with Nuxt 2 and bridge?
There was a `defineNuxtPlugin()` that isn't exposed by kit but could come in handy for this.

**Comment by lukaszflorczak** [comment]
Unfortunately, I don't have such a possibility so far. I assumed that `if (isVue2)` is a safe condition for that situation.

EDIT: But perhaps this is a wrong assumption. Does bridge use vue 3 or only compoisition api?
EDIT2: The `nuxt-demi` could be such a useful tool 🙃

**Comment by lukaszflorczak** [comment]
Ok. I tested it with `nuxt-bridge@3.0.0-27243104.5e903ae` and it looks that `if (isVue2)` works here. But it would probably be good if someone else tested it too. Here is a repository with Pinia and Nuxt 2 with Bridge: https://github.com/lukaszflorczak/nuxt2-bridge-demo/tree/test/pinia

**Comment by posva** [comment]
You are right, this is totally fine due to the if guard! Thanks!

**Pull request merged**
