### PR TITLE
perf(devtools/plunin): one proxy

### PR DESCRIPTION
**Pull request by so11y**
maybe one proxy store fast ，

### CODE REVIEW

**Comment by posva** [comment]
How is this improving perf? Do you have benchmarks?

**Comment by so11y** [comment]
my no use benchmark major test report，but use console.time contrast 
b916687ed563d1a8ba4b66d16cfdd4e
06dbe9bfd3331f0b221521aa883d038


```javascript 
  const userStore = useUserStore()
   console.time("test")
    for (let index = 0; index < 10; index++) {
         userStore.logout();
    }
    console.timeEnd("test");

```

**Comment by so11y** [comment]
> 我没有使用 benchmark 的主要测试报告，而是使用 console.time 对比
image
image


```javascript 
 const userStore = useUserStore()
   console.time("test")
    for (let index = 0; index < 10; index++) {
         userStore.logout();
    }
    console.timeEnd("test");
```

**Comment by so11y** [comment]
my no use benchmark major test report，but use console.time contrast
image
image

``` javascript 
 const userStore = useUserStore()
   console.time("test")
    for (let index = 0; index < 10; index++) {
         userStore.logout();
    }
    console.timeEnd("test");
```

**Comment by posva** [comment]
Ah but this won't work when calling the same action multiple times at the same time and it's dev only so it doesn't affect the final perf

**Pull request closed without merging**
