### PR TITLE
feat(devtools): expose selected store as global variable

### PR DESCRIPTION
**Pull request by Azurewarth0920**
Refs: #732

Clicking on a store in pinia devtools should make it available as a global variable

https://github.com/vuejs/pinia/assets/22590005/1b6fc1dd-9704-4bea-95cc-8def5f5bbc98

### CODE REVIEW

**Comment by posva** [comment]
This is nice! Maybe `$p` is too short. I also think we could have 2 properties:

- `$pinia` for the pinia associated with the store
- `$store` for the store in question

**Comment by Azurewarth0920** [comment]
Sorry, I didn't understand, did you mean

1. Assign the root pinia instance to variable `$pinia`?
2. Assign the currently selected store to variable `$store`?

**Comment by posva** [comment]
yes

**Comment by Azurewarth0920** [comment]
> https://github.com/vuejs/pinia/pull/2692#issuecomment-2168089160

Implemented in https://github.com/vuejs/pinia/pull/2692/commits/36a56a88f9b1f461e0d746b711404c810bc73c8c

**Review by posva — APPROVED** [review]
Thanks! I moved it to `globalThis` to support more runtimes

**Comment by acabreragnz** [comment]
Is this compatible with the new version of the devtools? It seems to not be working. (I didn't try it on the legacy devtools of the video.)

**Pull request merged**
