### PR TITLE
fix(docs): remove invalid character from id.

### PR DESCRIPTION
**Pull request by ByMykel**
When I try to click on any element with the dolar sign I get the following error:

image
image

This is happening because the `id` attribute has an invalid character (`$`).

https://pinia.vuejs.org/api/interfaces/pinia._StoreWithState.html

### CODE REVIEW

**Review by posva — CHANGES_REQUESTED** [review]
Thanks but this are generated. They should be changed in the generation script in the docs package folde

**Comment by ByMykel** [comment]
@posva ohh, should have taken more time to see it carefully. Can I still make the changes or is better to open an issue?

**Comment by posva** [comment]
Make the changes but don’t open an issue about this

**Review by posva — CHANGES_REQUESTED** [review]
I meant the changes to the script that generates the docs 😅

**Comment by ByMykel** [comment]
Doesn't `packages/docs/typedoc-markdown.js` generate the id's that are failing?

**Comment by posva** [comment]
Oh sorry, I didn't see on the phone. I'm starting to think this should actually be handled by vitepress 🤔 It should probably use `document.getElementById()` instead to avoid this specific problem. Vue Router does a similar thing

**Comment by ByMykel** [comment]
@posva  I'm not that good to understand your solution, but I think `$` is not a valid character for an `id`. When I link you https://pinia.vuejs.org/api/interfaces/pinia._StoreWithState.html#Methods-$patch you can see that the page don't scroll down to `$patch` section.

So using `document.getElementById()` would fix the click, but not when opening the link.

**Comment by Oscar-Raygoza** [comment]
oa

**Pull request closed without merging**
